name: ccddp_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_native_splash: 2.2.3+1
  
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_launcher_icons: 0.9.3
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter_icons:
  android: 'ic_launcher'
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/ic_launcher.png'

flutter_native_splash: 
  color: '#000000'
  # image: assets/images/splash/image.png
  # branding: assets/images/splash/branding.png
  # android_12: null
  # fullscreen: true

flutter:  
  assets: 
    - assets/
  uses-material-design: true